<a href="https://colab.research.google.com/github/dlawjd65/python/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

arr1 = np.arange(1, 21)
print(arr1)

arr2 = np.full((3, 4), 0)
print(arr2)

arr3 = np.full((5, 5), 1)
print(arr3)

arr4 = np.full((2, 3), 10)
print(arr4)


[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]
[[0 0 0 0]
 [0 0 0 0]
 [0 0 0 0]]
[[1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]
 [1 1 1 1 1]]
[[10 10 10]
 [10 10 10]]


In [ ]:
arr5 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12]])

print(arr5[:1])
print(arr5[-3:1])
print("-------------")
print(arr5[2:3])
print(arr5[-1:])
print(arr5[-1:3])
print("-------------")
print(arr5[1:2, 2:3])
print(arr5[-2:2, -2:3])
print("-------------")
print(arr5[1:3, 1:3])
print(arr5[-2:3, -3:3])
print("-------------")
print(arr5[1:3, 1:4])
print(arr5[-2:3, -3:4])



[[1 2 3 4]]
[[1 2 3 4]]
-------------
[[ 9 10 11 12]]
[[ 9 10 11 12]]
[[ 9 10 11 12]]
-------------
[[7]]
[[7]]
-------------
[[ 6  7]
 [10 11]]
[[ 6  7]
 [10 11]]
-------------
[[ 6  7  8]
 [10 11 12]]
[[ 6  7  8]
 [10 11 12]]


In [ ]:
arr6 = np.array([1, 2, 3, 4, 5])
arr7 = np.array([10, 20, 30, 40, 50])

print(arr6 + arr7)
print(arr6 * arr7)
print(arr6 + 10)
print(arr7 / 2)

[11 22 33 44 55]
[ 10  40  90 160 250]
[11 12 13 14 15]
[ 5. 10. 15. 20. 25.]


In [ ]:
scores = np.array([85, 92, 78, 90, 88, 76, 95, 89])

print(np.mean(scores))
print(np.max(scores))
print(np.min(scores))
print(np.std(scores))
print(np.sum(scores))



86.625
95
76
6.203577596838779
693


In [ ]:
import numpy as np

arr8 = np.arange(24)
arr_46 = np.reshape(arr8, (4, 6))
arr_38 = np.reshape(arr8, (3, 8))
arr_3d = np.reshape(arr8, (2, 3, 4)) # corrected newshape
print(arr8)
print(arr_46)
print(arr_38)
print(arr_3d)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]
[[ 0  1  2  3  4  5]
 [ 6  7  8  9 10 11]
 [12 13 14 15 16 17]
 [18 19 20 21 22 23]]
[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]
 [16 17 18 19 20 21 22 23]]
[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]


In [ ]:
data2 = np.array([15, 23, 8, 42, 16, 30, 7, 19, 25, 31])

print(data2[data2>=20])
print(data2[data2<=10])
print(data2[(data2>=15) & (data2<=25)])

[23 42 30 25 31]
[8 7]
[15 23 16 19 25]


In [ ]:
scores2 = np.array([[85, 90, 78],   # 학생1
                   [92, 88, 95],   # 학생2
                   [78, 82, 80],   # 학생3
                   [88, 85, 90],   # 학생4
                   [95, 92, 98]])  # 학생5
student_avg = scores2.mean(axis=1)
subject_avg = scores2.mean(axis=0)
all_avg = np.mean(scores2)
student_top = student_avg.argmax()+1

print(np.round(student_avg))
print(np.round(subject_avg))
print(np.round(all_avg))
print(np.max(scores2))
print(student_top)


[84. 92. 80. 88. 95.]
[88. 87. 88.]
88.0
98
5


In [ ]:
fahrenheit = np.array([32, 68, 86, 104, 122])

# 섭씨로 변환
celsius = (fahrenheit - 32) * 5/9

print(celsius)

[ 0. 20. 30. 40. 50.]


In [ ]:
A = np.array([[1, 2],
              [3, 4]])
B = np.array([[5, 6],
              [7, 8]])

# 행렬 곱셈 (dot product)
result = np.dot(A, B)
print(result)

[[19 22]
 [43 50]]


In [ ]:
data3 = np.random.randint(0, 101, 30)
data3_2d = data3.reshape(5, 6)

high_values = np.mean(data3[data3 >= 50])
print(data3_2d)
print(f"50 이상 값들의 평균: {high_values:.1f}")

[[ 23   9  93  33  91 100]
 [ 66  84  29  50  44  84]
 [ 37  63  19  47  63  58]
 [ 57   0  45  57  86  52]
 [ 23  54  39   2  95  81]]
[False False  True False  True  True  True  True False  True False  True
 False  True False False  True  True  True False False  True  True  True
 False  True False False  True  True]
50 이상 값들의 평균: 72.6


In [ ]:
data4 = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

normalized = (data4 - data4.min()) / (data4.max()-data4.min())
print(normalized)



[0.         0.11111111 0.22222222 0.33333333 0.44444444 0.55555556
 0.66666667 0.77777778 0.88888889 1.        ]


In [ ]:
arr9 = np.array([[1, 2, 3, 4],
                [5, 6, 7, 8],
                [9, 10, 11, 12],
                [13, 14, 15, 16]
                 ])

print(arr9[3:])

[[13 14 15 16]]
